# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

[![Codecov test coverage](https://codecov.io/gh/lisaxjiang/stat302project2part2/branch/master/graph/badge.svg)](https://codecov.io/gh/lisaxjiang/stat302project2part2?branch=master)
